import = ["/home/sharp/.config/alacritty/themes/themes/cyber_punk_neon.toml"]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"

[window]
opacity = 0.96

[window.padding]
x = 10
y = 10
