# !/bin/env zsh

CURRENT_DIR=$( cd "$( dirname -- ${(%):-%x} )" && pwd )
ZSHRC="$CURRENT_DIR/.zshrc"

if [ -L $ZSHRC ]
then
    CURRENT_DIR=$( dirname "$( readlink $ZSHRC )" )
fi

# Load Custom System Configuration
SHARED_CONFIG=$CURRENT_DIR/../shared

if [ -d $SHARED_CONFIG ]
then
    source $SHARED_CONFIG/init
fi

# Load zsh aliases
ZSH_ALIAS="$CURRENT_DIR/alias.zsh"
[ -f $ZSH_ALIAS ] && source $ZSH_ALIAS

# Prompt
eval "$(starship init zsh)"

