#!/bin/sh

# detect the shell
shell=`basename $SHELL`

source_completion() {
    local tool="${1}"

    if command -v $tool &> /dev/null; then
        source <($tool completion $shell)
    fi
}

source_completion minikube
source_completion gitleaks

